apiVersion: v1
kind: Secret
metadata:
  name: authentication-secrets
  namespace: battlescope
type: Opaque
stringData:
  encryption-key: "a09e63058419e42198893ac433d97414688ebe7771f412719e0e3512300fb662"
  session-secret: "0nJZlwv/BQcv0tUwSEwluQgKLtcJd1N/nBEkJeVXJVE="
  eve-client-secret: "eat_2HkUBZFd5CVll5v7KBYBoz73TfBIGqyNh_4PQzoi"
  db-password: "battlescope_password"
