apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: battlescope
type: Opaque
stringData:
  POSTGRES_DB: battlescope
  POSTGRES_USER: battlescope
  POSTGRES_PASSWORD: aA1w0Kpc9Rz2
