apiVersion: batch/v1
kind: CronJob
metadata:
  name: scheduler
  namespace: battlescope
spec:
  schedule: '*/10 * * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: scheduler
        spec:
          restartPolicy: OnFailure
          containers:
            - name: scheduler
              image: docker.io/petdog/battlescope-scheduler:latest
              imagePullPolicy: Always
              command:
                - node
                - dist/backend/scheduler/src/index.js
              env:
                - name: OTEL_SERVICE_NAME
                  value: 'battlescope-scheduler'
              envFrom:
                - secretRef:
                    name: battlescope-secrets
                - configMapRef:
                    name: battlescope-config
